create schema api;	-- Kestra demanded it be lowercase...

CREATE TABLE api.stg_the_odds_api (
  id varchar,
  sport_key varchar,
  sport_title varchar,
  commence_time varchar,
  home_team varchar,
  away_team varchar,   
  full_json json
);


CREATE TABLE api.the_odds_api (
  the_odds_api_id bigint GENERATED BY DEFAULT AS IDENTITY,
  id varchar,
  sport_key varchar,
  sport_title varchar,
  commence_time varchar,
  home_team varchar,
  away_team varchar,   
  full_json json,
  game_id bigint,
  home_team_id int,
  away_team_id int,
  imported boolean default (false),
  insert_dt timestamp not null default now()
);

CREATE TABLE api.the_odds_api_bet (
  the_odds_api_bet_id bigint GENERATED BY DEFAULT AS IDENTITY,
  the_odds_api_id bigint,
  id varchar(100),
  bookmakers_key varchar,
  bookmakers_title varchar,
  markets_key varchar,
  markets_last_update varchar,
  name varchar(100),  
  price varchar(100),  
  point varchar(100),  
  imported boolean default (false),
  insert_dt timestamp not null default now()
);


-- Weather
-- Actual, Forecast Flag??
-- start/end dates when

-- Could do morning forecasts(Daily's) and again at time of games in evening without forecasts


CREATE TABLE api.open_weather (
  OPENWEATHER_API_ID bigint GENERATED BY DEFAULT AS IDENTITY,
  INSERT_DT timestamp not null default now(),
  LAT decimal(8,6) not NULL,
  LON decimal(9,6) not NULL,
  CURRENT_EPOCH bigint not NULL,
  CURRENT_DT date not null, -- to_timestamp(CURRENT_EPOCH)::date
  CURRENT_JSON json,
  DAILY_JSON json,
  IMPORTED bit default ('0')
);

CREATE TABLE api.stg_open_weather (
  LAT decimal(8,6) not NULL,
  LON decimal(9,6) not NULL,
  CURRENT_EPOCH bigint not NULL,
  CURRENT_JSON json,
  DAILY_JSON json
);


--SELECT extract(epoch FROM now());				-- 1737640390.593964
--SELECT to_timestamp(1737640390.593964);			-- 2025-01-23 07:53:10.593 -0600
--SELECT to_timestamp(1737640390);				-- 2025-01-23 07:53:10.000 -0600
--SELECT to_timestamp(1737640390.593964)::date;	-- 2025-01-23
----
----select -123.456789::decimal(6,3);
--
--select CURRENT_DATE - CURRENT_DATE + 2;
--select CURRENT_DATE + 2;




-- Open Weather API:

-- Daily table for forecasts & sports that ain't played outside
-- Game Time table for historic usecase of results based on weather during game.

CREATE TABLE api.weather_daily (
  weather_daily_id bigint GENERATED BY DEFAULT AS IDENTITY,
  insert_dt timestamp not null default now(),
  lat decimal(8,6) not null,
  lon decimal(9,6) not null,
  daily_epoch bigint not null,
  daily_dt date not null,	-- to_timestamp(DAILY_EPOCH)::date
  num_days_ahead smallint not null, -- CURRENT_DATE - to_timestamp(DAILY_EPOCH)::date
  		-- For Historical will load in with -1 value ??
  weather_id smallint,    
  temp_min decimal(6,3),
  temp_max decimal(6,3),
  temp_morn decimal(6,3),
  temp_eve decimal(6,3),
  wind_speed decimal(6,3),
  snow_vol_mm decimal(6,3),
  rain_vol_mm decimal(6,3)
);


CREATE TABLE api.weather_at_game (
  weather_at_game_id bigint GENERATED BY DEFAULT AS IDENTITY,
  game_id bigint NOT NULL, 
  game_epoch bigint not null,
  game_dt date not null,
  game_time time not null,
  weather_id smallint,  
  temp decimal(6,3),
  wind_speed decimal(6,3),
  rain_mm_h decimal(6,3),
  snow_mm_h decimal(6,3),
  is_hist_avg bit default ('0'),
  insert_dt timestamp not null default now()
);





---------------------------------------------
-- MLB


CREATE TABLE api.stg_mlb_sched (
	GAME_ID int4,
	GAME_DT date NOT NULL,
	GAME_TIME timestamp null,
	HOME_TEAM varchar NOT NULL,
	AWAY_TEAM varchar NOT NULL
);

CREATE TABLE api.stg_mlb_sched_unknown (
	GAME_ID int4,
	GAME_DT date NOT NULL,
	GAME_TIME timestamp null,
	HOME_TEAM varchar NOT NULL,
	AWAY_TEAM varchar NOT null,
	REASON varchar,
  	INSERT_DT timestamp not null default now()
);



-- DROP TABLE api.mlb_api_batting;

CREATE TABLE api.mlb_api_batting (
	gamepk varchar(20) NOT NULL,
	gamedate date NOT NULL,
	team_id int4 NOT NULL,
	personid int4 NOT NULL,
	name text NOT NULL,
	position text NULL,
	battingorder text NULL,
	ab int4 NULL,
	r int4 NULL,
	h int4 NULL,
	doubles int4 NULL,
	triples int4 NULL,
	hr int4 NULL,
	rbi int4 NULL,
	sb int4 NULL,
	bb int4 NULL,
	k int4 NULL,
	lob int4 NULL,
	avg numeric(4, 3) NULL,
	obp numeric(4, 3) NULL,
	slg numeric(4, 3) NULL,
	substitution text NULL,
	note text NULL,
	note_description text NULL,
	CONSTRAINT mlb_api_batting_pkey PRIMARY KEY (gamepk, gamedate, team_id, personid)
);


-- DROP TABLE api.mlb_api_meta;

CREATE TABLE api.mlb_api_meta (
	gamepk varchar(20) NOT NULL,
	gamedate date NOT NULL,
	umpires text NULL,
	weather text NULL,
	wind text NULL,
	CONSTRAINT mlb_api_meta_pkey PRIMARY KEY (gamepk, gamedate)
);


-- DROP TABLE api.mlb_api_pitching;

CREATE TABLE api.mlb_api_pitching (
	gamepk varchar(20) NOT NULL,
	gamedate date NOT NULL,
	team_id int4 NOT NULL,
	personid int4 NOT NULL,
	name text NOT NULL,
	ip numeric(4, 1) NULL,
	h int4 NULL,
	r int4 NULL,
	er int4 NULL,
	bb int4 NULL,
	k int4 NULL,
	hr int4 NULL,
	p int4 NULL,
	s int4 NULL,
	era numeric(5, 2) NULL,
	note text NULL,
	CONSTRAINT mlb_api_pitching_pkey PRIMARY KEY (gamepk, gamedate, team_id, personid)
);



---------------------------------------------
-- NBA


-- DROP TABLE api.nba_api_traditional_box_score;

CREATE TABLE api.nba_api_traditional_box_score (
	game_id varchar(15) NOT NULL,
	team_id int4 NOT NULL,
	team_abbreviation text NOT NULL,
	team_city text NOT NULL,
	player_id int4 NOT NULL,
	player_name text NOT NULL,
	nickname text NULL,
	start_position bpchar(2) NULL,
	comment text NULL,
	minutes_played varchar(25) NULL,
	field_goals_made numeric(4, 1) NULL,
	field_goals_attempted numeric(4, 1) NULL,
	field_goal_pct numeric(4, 3) NULL,
	three_pointers_made numeric(4, 1) NULL,
	three_pointers_attempted numeric(4, 1) NULL,
	three_point_pct numeric(4, 3) NULL,
	free_throws_made numeric(4, 1) NULL,
	free_throws_attempted numeric(4, 1) NULL,
	free_throw_pct numeric(4, 3) NULL,
	offensive_rebounds numeric(4, 1) NULL,
	defensive_rebounds numeric(4, 1) NULL,
	total_rebounds numeric(4, 1) NULL,
	assists numeric(4, 1) NULL,
	steals numeric(4, 1) NULL,
	blocks numeric(4, 1) NULL,
	turnovers numeric(4, 1) NULL,
	personal_fouls numeric(4, 1) NULL,
	points numeric(4, 1) NULL,
	plus_minus numeric(4, 1) NULL,
	CONSTRAINT nba_api_traditional_box_score_pkey PRIMARY KEY (game_id, player_id)
);




---------------------------------------------
-- NHL


-- DROP TABLE api.nhl_api_box_score;

CREATE TABLE api.nhl_api_box_score (
	gameid int4 NOT NULL,
	date date NOT NULL,
	team varchar(10) NOT NULL,
	playerid int4 NOT NULL,
	playername varchar(100) NOT NULL,
	position varchar(10) NOT NULL,
	goals int4 NULL,
	assists int4 NULL,
	points int4 NULL,
	plusminus int4 NULL,
	pim int4 NULL,
	hits int4 NULL,
	sog int4 NULL,
	blockedshots int4 NULL,
	giveaways int4 NULL,
	takeaways int4 NULL,
	timeonice interval NULL,
	shifts int4 NULL,
	faceoffwinningpctg numeric(5, 2) NULL,
	CONSTRAINT nhl_api_box_score_pkey PRIMARY KEY (gameid, playerid)
);


-- DROP TABLE api.nhl_api_goalie_box_score;

CREATE TABLE api.nhl_api_goalie_box_score (
	gameid int4 NOT NULL,
	date date NOT NULL,
	team varchar(10) NOT NULL,
	playerid int4 NOT NULL,
	playername varchar(100) NOT NULL,
	position varchar(10) NOT NULL,
	evenstrengthshotsagainst varchar(10) NULL,
	powerplayshotsagainst varchar(10) NULL,
	shorthandedshotsagainst varchar(10) NULL,
	saveshotsagainst varchar(10) NULL,
	savepctg numeric(5, 3) NULL,
	evenstrengthgoalsagainst int4 NULL,
	powerplaygoalsagainst int4 NULL,
	shorthandedgoalsagainst int4 NULL,
	pim int4 NULL,
	goalsagainst int4 NULL,
	timeonice varchar(10) NULL,
	shotsagainst int4 NULL,
	saves int4 NULL,
	CONSTRAINT nhl_api_goalie_box_score_pkey PRIMARY KEY (gameid, playerid)
);



---------------------------------------------
-- NFL

create TABLE api.stg_nfl_defensive_box (
    event_id               BIGINT NOT NULL,
    team_id                INT NOT NULL,
    team_abbr              VARCHAR(10),
    team_name              VARCHAR(100),
    athlete_id             BIGINT,
    athlete_name           VARCHAR(100),
    athlete_jersey         VARCHAR(10),
    totalTackles            INT,
    soloTackles             INT,
    sacks                   NUMERIC(4,1),
    tacklesForLoss          INT,
    passesDefended          INT,
    QBHits                  INT,
    defensiveTouchdowns     INT,
    interceptions           INT,
    interceptionYards       INT,
    interceptionTouchdowns  INT
    -- hurries                 INT,
);



CREATE TABLE api.stg_nfl_offensive_box (
    event_id                BIGINT NOT NULL,
    team_id                 INT NOT NULL,
    team_abbr               VARCHAR(10),
    team_name               VARCHAR(100),
    athlete_id              BIGINT,
    athlete_name            VARCHAR(100),
    athlete_jersey          VARCHAR(10),
    passingYards            INT,
    yardsPerPassAttempt     NUMERIC(5,2),
    passingTouchdowns       INT,
    interceptions           INT,
    adjQBR                  NUMERIC(5,2),
    rushingAttempts         INT,
    rushingYards            INT,
    yardsPerRushAttempt     NUMERIC(5,2),
    rushingTouchdowns       INT,
    longRushing             INT,
    receptions              INT,
    receivingYards          INT,
    yardsPerReception       NUMERIC(5,2),
    receivingTouchdowns     INT,
    longReception           INT,
    receivingTargets        INT,
--    QBRating                NUMERIC(5,2),
    passingCompletions      INT,
    passingAttempts         INT,
    sacks                   INT,
    sackYardsLost           INT
);

CREATE TABLE api.stg_nfl_special_teams_box (
    event_id                   BIGINT NOT NULL,
    team_id                    INT NOT NULL,
    team_abbr                  VARCHAR(10),
    team_name                  VARCHAR(100),
    athlete_id                 BIGINT,
    athlete_name               VARCHAR(100),
    athlete_jersey             VARCHAR(10),
    kickReturns               INT,
    kickReturnYards          INT,
    yardsPerKickReturn      NUMERIC(5,2),
    longKickReturn           INT,
    kickReturnTouchdowns     INT,
    puntReturns                INT,
    puntReturnYards             INT,
    yardsPerPuntReturn          NUMERIC(5,2),
    longPuntReturn              INT,
    puntReturnTouchdowns        INT,
    fieldGoalPct             NUMERIC(5,2),
    longFieldGoalMade       INT,
    totalKickingPoints       INT,
    punts                      INT,
    puntYards                 INT,
    grossAvgPuntYards       NUMERIC(5,2),
    touchbacks                 INT,
    puntsInside20            INT,
    longPunt                  INT,
    xpSuccess                 INT,
    xpAttempts                INT,
    fgSuccess                 INT,
    fgAttempts                INT
);


CREATE TABLE api.stg_nfl_game_team_summary (
    event_id                  BIGINT NOT NULL,
    gamedate                  TIMESTAMP,
    season                    INT,
    season_type               INT,
    gameweek                  INT,
    venue_full_name           VARCHAR(150),
    venue_city                VARCHAR(100),
    venue_state               VARCHAR(50),
    venue_zip                 VARCHAR(20),
    venue_country             VARCHAR(50),
    venue_grass               BOOLEAN,
    attendance                INT,
    status_type               VARCHAR(50),
    status_detail             VARCHAR(50),
    neutral_site              BOOLEAN,
    conference_competition    BOOLEAN,
    team_id                   INT NOT NULL,
    team_abbr                 VARCHAR(10),
    team_name                 VARCHAR(100),
    home_away                 VARCHAR(10),
    team_score                INT,
    spread                    NUMERIC(5,2),
    over_under                NUMERIC(5,2),
    firstDowns               INT,
    firstDownsPassing       INT,
    firstDownsRushing       INT,
    firstDownsPenalty       INT,
    totalOffensivePlays     INT,
    totalYards               INT,
    yardsPerPlay            NUMERIC(5,2),
    totalDrives              INT,
    netPassingYards         INT,
    yardsPerPass            NUMERIC(5,2),
    interceptions             INT,
    rushingYards             INT,
    rushingAttempts          INT,
    yardsPerRushAttempt    NUMERIC(5,2),
    turnovers                 INT,
    fumblesLost              INT,
    defensiveTouchdowns      INT,
    possessionTime           INTERVAL,
    passingCompletions       INT,
    passingAttempts          INT,
    thirddownSuccess        INT,
    thirddownAttempts       INT,
    fourthdownSuccess       INT,
    fourthdownAttempts      INT,
    sacks                     INT,
    sackYardsLost           INT,
    redZoneSuccess          NUMERIC(5,2),
    penalties                 INT,
    PenaltyYards             INT
);


CREATE TABLE api.stg_nfl_schedule (
	gamedate timestamptz NULL,
	"name" varchar(250) NULL,
	shortname varchar(100) NULL,
	week_number int4 NULL,
	season_year int4 NULL,
	season_type int4 NULL,
	season_slug varchar(50) NULL,
	status_period int4 NULL,
	home_score int4 NULL,
	home_team varchar(100) NULL,
	home_abbr varchar(100) NULL,
	home_short varchar(100) NULL,
	home_team_id int4 NULL,
	game_id int8 NOT NULL,
	seasontype int4 NULL,
	seasontypelabel varchar(100) NULL,
	gameweek int4 NULL,
	weeklabel varchar(100) NULL,
	q1_home int4 NULL,
	q2_home int4 NULL,
	q3_home int4 NULL,
	q4_home int4 NULL,
	q5_home int4 NULL,
	away_score int4 NULL,
	away_team varchar(100) NULL,
	away_abbr varchar(100) NULL,
	away_short varchar(100) NULL,
	away_team_id int4 NULL,
	q1_away int4 NULL,
	q2_away int4 NULL,
	q3_away int4 NULL,
	q4_away int4 NULL,
	q5_away int4 NULL
);





---------------------------------------------
-- CFB


create TABLE api.stg_cfb_defensive_box (
    event_id               BIGINT NOT NULL,
    team_id                INT NOT NULL,
    team_abbr              VARCHAR(10),
    team_name              VARCHAR(100),
    athlete_id             BIGINT,
    athlete_name           VARCHAR(100),
    athlete_jersey         VARCHAR(10),
    totalTackles            INT,
    soloTackles             INT,
    sacks                   NUMERIC(4,1),
    tacklesForLoss          INT,
    passesDefended          INT,
    QBHits                  INT,
    defensiveTouchdowns     INT,
    interceptions           INT,
    interceptionYards       INT,
    interceptionTouchdowns  INT,
    hurries                 INT
);



CREATE TABLE api.stg_cfb_offensive_box (
    event_id                BIGINT NOT NULL,
    team_id                 INT NOT NULL,
    team_abbr               VARCHAR(10),
    team_name               VARCHAR(100),
    athlete_id              BIGINT,
    athlete_name            VARCHAR(100),
    athlete_jersey          VARCHAR(10),
    passingYards            INT,
    yardsPerPassAttempt     NUMERIC(5,2),
    passingTouchdowns       INT,
    interceptions           INT,
--    adjQBR                  NUMERIC(5,2),
    rushingAttempts         INT,
    rushingYards            INT,
    yardsPerRushAttempt     NUMERIC(5,2),
    rushingTouchdowns       INT,
    longRushing             INT,
    receptions              INT,
    receivingYards          INT,
    yardsPerReception       NUMERIC(5,2),
    receivingTouchdowns     INT,
    longReception           INT,
    receivingTargets        INT,
    QBRating                NUMERIC(5,2),
    passingCompletions      INT,
    passingAttempts         INT,
    sacks                   INT,
    sackYardsLost           INT
);

CREATE TABLE api.stg_cfb_special_teams_box (
    event_id                   BIGINT NOT NULL,
    team_id                    INT NOT NULL,
    team_abbr                  VARCHAR(10),
    team_name                  VARCHAR(100),
    athlete_id                 BIGINT,
    athlete_name               VARCHAR(100),
    athlete_jersey             VARCHAR(10),
    kickReturns               INT,
    kickReturnYards          INT,
    yardsPerKickReturn      NUMERIC(5,2),
    longKickReturn           INT,
    kickReturnTouchdowns     INT,
    puntReturns                INT,
    puntReturnYards             INT,
    yardsPerPuntReturn          NUMERIC(5,2),
    longPuntReturn              INT,
    puntReturnTouchdowns        INT,
    fieldGoalPct             NUMERIC(5,2),
    longFieldGoalMade       INT,
    totalKickingPoints       INT,
    punts                      INT,
    puntYards                 INT,
    grossAvgPuntYards       NUMERIC(5,2),
    touchbacks                 INT,
    puntsInside20            INT,
    longPunt                  INT,
    xpSuccess                 INT,
    xpAttempts                INT,
    fgSuccess                 INT,
    fgAttempts                INT
);


CREATE TABLE api.stg_cfb_game_team_summary (
    event_id                  BIGINT NOT NULL,
    gamedate                  TIMESTAMP,
    season                    INT,
    season_type               INT,
    gameweek                  INT,
    venue_full_name           VARCHAR(150),
    venue_city                VARCHAR(100),
    venue_state               VARCHAR(50),
    venue_zip                 VARCHAR(20),
    venue_country             VARCHAR(50),
    venue_grass               BOOLEAN,
    attendance                INT,
    status_type               VARCHAR(50),
    status_detail             VARCHAR(50),
    neutral_site              BOOLEAN,
    conference_competition    BOOLEAN,
    team_id                   INT NOT NULL,
    team_abbr                 VARCHAR(10),
    team_name                 VARCHAR(100),
    home_away                 VARCHAR(10),
    team_score                INT,
    spread                    NUMERIC(5,2),
    over_under                NUMERIC(5,2),
    firstDowns               INT,
    firstDownsPassing       INT,
    firstDownsRushing       INT,
    firstDownsPenalty       INT,
    totalOffensivePlays     INT,
    totalYards               INT,
    yardsPerPlay            NUMERIC(5,2),
    totalDrives              INT,
    netPassingYards         INT,
    yardsPerPass            NUMERIC(5,2),
    interceptions             INT,
    rushingYards             INT,
    rushingAttempts          INT,
    yardsPerRushAttempt    NUMERIC(5,2),
    turnovers                 INT,
    fumblesLost              INT,
    defensiveTouchdowns      INT,
    possessionTime           INTERVAL,
    passingCompletions       INT,
    passingAttempts          INT,
    thirddownSuccess        INT,
    thirddownAttempts       INT,
    fourthdownSuccess       INT,
    fourthdownAttempts      INT,
    sacks                     INT,
    sackYardsLost           INT,
    redZoneSuccess          NUMERIC(5,2),
    penalties                 INT,
    PenaltyYards             INT
);


CREATE TABLE api.stg_cfb_schedule (
	gamedate timestamptz NULL,
	"name" varchar(250) NULL,
	shortname varchar(100) NULL,
	week_number int4 NULL,
	season_year int4 NULL,
	season_type int4 NULL,
	season_slug varchar(50) NULL,
	status_period int4 NULL,
	home_score int4 NULL,
	home_team varchar(100) NULL,
	home_abbr varchar(100) NULL,
	home_short varchar(100) NULL,
	home_team_id int4 NULL,
	game_id int8 NOT NULL,
	seasontype int4 NULL,
	seasontypelabel varchar(100) NULL,
	gameweek int4 NULL,
	weeklabel varchar(100) NULL,
	q1_home int4 NULL,
	q2_home int4 NULL,
	q3_home int4 NULL,
	q4_home int4 NULL,
	q5_home int4 NULL,
	away_score int4 NULL,
	away_team varchar(100) NULL,
	away_abbr varchar(100) NULL,
	away_short varchar(100) NULL,
	away_team_id int4 NULL,
	q1_away int4 NULL,
	q2_away int4 NULL,
	q3_away int4 NULL,
	q4_away int4 NULL,
	q5_away int4 NULL
);
