create schema "api";	-- Kestra demanded it be lowercase...

CREATE TABLE "api"."stg_the_odds_api" (
  "id" varchar,
  "sport_key" varchar,
  "sport_title" varchar,
  "commence_time" varchar,
  "home_team" varchar,
  "away_team" varchar,   
  "full_json" json
);


CREATE TABLE "api"."the_odds_api" (
  "THE_ODDs_API_ID" bigint GENERATED BY DEFAULT AS IDENTITY,
  "id" varchar,
  "sport_key" varchar,
  "sport_title" varchar,
  "commence_time" varchar,
  "home_team" varchar,
  "away_team" varchar,   
  "full_json" json,
  "IMPORTED" bit default ('0'),
  "INSERT_DT" timestamp not null default now()
);

CREATE TABLE "api"."the_odds_api_bet" (
  "THE_ODDs_API_BET_ID" bigint GENERATED BY DEFAULT AS IDENTITY,
  "THE_ODDs_API_ID" bigint,
  "id" varchar(100),
  "bookmakers_key" varchar,
  "bookmakers_title" varchar,
  "markets_key" varchar,
  "markets_last_update" varchar,
  "name" varchar(100),  
  "price" varchar(100),  
  "point" varchar(100),  
  "IMPORTED" bit default ('0'),
  "INSERT_DT" timestamp not null default now()
);


-- Weather
-- Actual, Forecast Flag??
-- start/end dates when

-- Could do morning forecasts(Daily's) and again at time of games in evening without forecasts


CREATE TABLE "api"."open_weather" (
  "OPENWEATHER_API_ID" bigint GENERATED BY DEFAULT AS IDENTITY,
  "INSERT_DT" timestamp not null default now(),
  "LAT" decimal(8,6) not NULL,
  "LON" decimal(9,6) not NULL,
  "CURRENT_EPOCH" bigint not NULL,
  "CURRENT_DT" date not null, -- to_timestamp("CURRENT_EPOCH")::date
  "CURRENT_JSON" json,
  "DAILY_JSON" json,
  "IMPORTED" bit default ('0')
);

CREATE TABLE "api"."stg_open_weather" (
  "LAT" decimal(8,6) not NULL,
  "LON" decimal(9,6) not NULL,
  "CURRENT_EPOCH" bigint not NULL,
  "CURRENT_JSON" json,
  "DAILY_JSON" json
);


--SELECT extract(epoch FROM now());				-- 1737640390.593964
--SELECT to_timestamp(1737640390.593964);			-- 2025-01-23 07:53:10.593 -0600
--SELECT to_timestamp(1737640390);				-- 2025-01-23 07:53:10.000 -0600
--SELECT to_timestamp(1737640390.593964)::date;	-- 2025-01-23
----
----select -123.456789::decimal(6,3);
--
--select CURRENT_DATE - CURRENT_DATE + 2;
--select CURRENT_DATE + 2;




CREATE TABLE "api"."stg_mlb_sched" (
	"GAME_ID" int4,
	"GAME_DT" date NOT NULL,
	"GAME_TIME" timestamp null,
	"HOME_TEAM" varchar NOT NULL,
	"AWAY_TEAM" varchar NOT NULL
);

CREATE TABLE "api"."stg_mlb_sched_unknown" (
	"GAME_ID" int4,
	"GAME_DT" date NOT NULL,
	"GAME_TIME" timestamp null,
	"HOME_TEAM" varchar NOT NULL,
	"AWAY_TEAM" varchar NOT null,
	"REASON" varchar,
  	"INSERT_DT" timestamp not null default now()
);


