services:
  postgres:
    image: postgres:17.4
    container_name: unit_postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local