CREATE TABLE IF NOT EXISTS src.basket_espn_schedule (
	league_id   INT NOT NULL,   -- 1 NBA, 6 CBB
	game_id     int4,
    gamedate    TIMESTAMPTZ,
	name        varchar(200),
	shortName   varchar(100),
	season_year int4,
	season_type int4,
	season_slug varchar(100),
	status_period   int4,
	home_score      int4,
	home_team   varchar(100),
	home_abbr   varchar(100),
	home_short  varchar(100),
	home_team_id    int4,
	q1_home   int4,
	q2_home   int4,
	q3_home   int4,
	q4_home   int4,
	q5_home   int4,
	away_score  int4,
	away_team   varchar(100),
	away_abbr   varchar(100),
	away_short  varchar(100),
	away_team_id    int4,
	q1_away   int4,
	q2_away   int4,
	q3_away   int4,
	q4_away   int4,
	q5_away   int4 NULL
);