CREATE TABLE src.foot_espn_box_defensive (
    league_id              INT NOT NULL,       -- Added on insert from csv, 2 NFL, 5 CFB
    event_id               BIGINT NOT NULL,
    team_id                INT NOT NULL,
    team_abbr              VARCHAR(10),
    team_name              VARCHAR(100),
    athlete_id             BIGINT,
    athlete_name           VARCHAR(100),
    athlete_jersey         VARCHAR(10),
    totalTackles            INT,
    soloTackles             INT,
    sacks                   NUMERIC(4,1),
    tacklesForLoss          INT,
    passesDefended          INT,
    QBHits                  INT,
    defensiveTouchdowns     INT,
    interceptions           INT,
    interceptionYards       INT,
    interceptionTouchdowns  INT,
    hurries                 INT,
    foot_espn_box_defensive_id  bigint GENERATED BY DEFAULT AS IDENTITY,
    PRIMARY KEY (league_id, event_id, team_id, athlete_id)
);