CREATE TABLE IF NOT EXISTS src.kalshi_game (
  kalshi_game_id bigint GENERATED BY DEFAULT AS IDENTITY,
  home_kalshi_markets_id bigint,
  away_kalshi_markets_id bigint,
  game_id bigint,
  game_concat varchar,
  game_dt date,
  home_team_id int,
  away_team_id int,
  home_yes int,
  home_volume int,
  home_liquidity bigint,
  away_yes int,
  away_volume int,
  away_liquidity bigint,
  is_imported boolean default (false),
  is_latest boolean default (false),
  insert_ts timestamp not null default now()
);