CREATE TABLE IF NOT EXISTS src.the_odds_api (
    the_odds_api_id bigint GENERATED BY DEFAULT AS IDENTITY,
    odd_hash varchar(32) NOT NULL, -- md5(id || bookmakers_key || markets_key || market_name || (markets_last_update_ts)::varchar )
    id varchar(50) NOT NULL,
    bookmakers_key varchar(50) NOT NULL,
    markets_key varchar(50) NOT NULL,
    market_name varchar(50) NOT NULL,
    markets_last_update_ts timestamp NOT NULL,
    sport_key varchar(50) NULL,
    sport_title varchar(50) NULL,
    commence_ts timestamp NULL,
    home_team varchar(100) NULL,
    away_team varchar(100) NULL,
    bookmakers_title varchar(50) NULL,
    price float4 NULL,
    point float4 NULL,
    insert_ts timestamp not null default now()
);