CREATE TABLE IF NOT EXISTS src.weather_forecast (
  weather_forecast_id bigint GENERATED BY DEFAULT AS IDENTITY,
  insert_ts timestamp not null default now(),
  lat decimal(8,6) not null,
  lon decimal(9,6) not null,
  daily_epoch bigint not null,
  daily_dt date not null,	-- to_timestamp(DAILY_EPOCH)::date
  num_days_ahead smallint not null, -- CURRENT_DATE - to_timestamp(DAILY_EPOCH)::date
  		-- For Historical will load in with -1 value ??
  weather_id smallint,    
  temp_min decimal(6,3),
  temp_max decimal(6,3),
  temp_morn decimal(6,3),
  temp_eve decimal(6,3),
  wind_speed decimal(6,3),
  snow_vol_mm decimal(6,3),
  rain_vol_mm decimal(6,3)
);