CREATE TABLE IF NOT EXISTS utility.weather_game (
  weather_game_id bigint GENERATED BY DEFAULT AS IDENTITY,
  game_id bigint NOT NULL, 
  game_epoch bigint not null,
  game_dt date not null,
  game_time time not null,
  weather_id smallint,  
  temp decimal(6,3),
  wind_speed decimal(6,3),
  rain_mm_h decimal(6,3),
  snow_mm_h decimal(6,3),
  is_hist_avg bit default ('0'),
  insert_ts timestamp not null default now()
);