CREATE TABLE IF NOT EXISTS etl.all_the_odds_api_bet (
  the_odds_api_bet_id bigint GENERATED BY DEFAULT AS IDENTITY,
  the_odds_api_id bigint,
  id varchar(100),
  bookmakers_key varchar,
  bookmakers_title varchar,
  markets_key varchar,
  markets_last_update varchar,
  name varchar(100),  
  price varchar(100),  
  point varchar(100),  
  imported boolean default (false),
  insert_ts timestamp not null default now()
);