CREATE TABLE IF NOT EXISTS etl.all_the_odds_api_bet (
  the_odds_api_bet_id bigint GENERATED BY DEFAULT AS IDENTITY,
  the_odds_api_id bigint,
  id varchar(100),
  sport_key varchar,
  sport_title varchar,
  commence_time varchar,
  home_team varchar,
  away_team varchar,   
  bookmakers_key varchar,
  bookmakers_title varchar,
  markets_key varchar,
  markets_last_update varchar,
  name varchar(100),  
  price varchar(100),  
  point varchar(100),  
  odd_hash varchar(32) NOT NULL, -- md5(id || bookmakers_key || markets_key || "name" || (markets_last_update::timestamp)::varchar )
  imported boolean default (false),
  insert_ts timestamp not null default now()
);