CREATE TABLE IF NOT EXISTS etl.all_kalshi_market (
  kalshi_market_id bigint GENERATED BY DEFAULT AS IDENTITY,
  event_ticker varchar,
  ticker varchar,
  expected_expiration_time TIMESTAMPTZ,
  title varchar,
  yes_sub_title varchar,
  volume float4,
  volume_24h float4,
  yes_ask float4,
  yes_bid float4,
  liquidity float4,
  open_interest float4,
  rules_primary varchar,
  status varchar,
  imported boolean default (false),
  insert_ts timestamp not null default now()
);