CREATE TABLE IF NOT EXISTS etl.all_foot_espn_weeks (
  	week_id bigint GENERATED BY DEFAULT AS IDENTITY,
	league_id smallint,
	yr smallint,
	season_label varchar,
	season_value smallint,
	week_label varchar,
	week_value smallint,
	week_start_date date,
	week_end_date date,
	imported boolean default (false),
	insert_ts timestamp not null default now()
);