CREATE TABLE IF NOT EXISTS etl.all_kalshi_game (
    kalshi_game_id bigint GENERATED BY DEFAULT AS IDENTITY,
	league_id smallint NULL,
	game_dt date NULL,
    event_ticker varchar NULL,
    pull_dt date NULL,
    kalshi_hash varchar(32) NOT NULL, -- md5(league_id::varchar || game_date || event_ticker || pull_dt || h.volume || a.volume )
	home_kalshi_market_id int8 NULL,
	away_kalshi_market_id int8 NULL,
	home_team varchar NULL,
	away_team varchar NULL,
	home_yes float4 NULL,
	home_volume float4 NULL,
	home_liquidity float4 NULL,
	away_yes float4 NULL,
	away_volume float4 NULL,
	away_liquidity float4 NULL,
	imported boolean default (false),
	insert_ts timestamp not null default now()
);