CREATE TABLE IF NOT EXISTS api.all_the_odds_api (
  the_odds_api_id bigint GENERATED BY DEFAULT AS IDENTITY,
  id varchar,
  sport_key varchar,
  sport_title varchar,
  commence_time varchar,
  home_team varchar,
  away_team varchar,   
  full_json json,
  game_id bigint,
  home_team_id int,
  away_team_id int,
  imported boolean default (false),
  insert_ts timestamp not null default now()
);