CREATE TABLE IF NOT EXISTS api.open_weather (
  openweather_api_id bigint GENERATED BY DEFAULT AS IDENTITY,
  insert_ts timestamp not null default now(),
  lat decimal(8,6) not NULL,
  lon decimal(9,6) not NULL,
  current_epoch bigint not NULL,
  current_dt date not null, -- to_timestamp(CURRENT_EPOCH)::date
  current_json json,
  daily_json json,
  imported bit default ('0')
);