CREATE TABLE IF NOT EXISTS etl.stg_foot_espn_box_special (
	event_id int8 NOT NULL,
	team_id int4 NOT NULL,
	team_abbr varchar(10) NULL,
	team_name varchar(100) NULL,
	athlete_id int8 NULL,
	athlete_name varchar(100) NULL,
	athlete_jersey varchar(10) NULL,
	kickreturns int4 NULL,
	kickreturnyards int4 NULL,
	yardsperkickreturn numeric(5, 2) NULL,
	longkickreturn int4 NULL,
	kickreturntouchdowns int4 NULL,
	puntreturns int4 NULL,
	puntreturnyards int4 NULL,
	yardsperpuntreturn numeric(5, 2) NULL,
	longpuntreturn int4 NULL,
	puntreturntouchdowns int4 NULL,
	fieldgoalpct numeric(5, 2) NULL,
	longfieldgoalmade int4 NULL,
	totalkickingpoints int4 NULL,
	punts int4 NULL,
	puntyards int4 NULL,
	grossavgpuntyards numeric(5, 2) NULL,
	touchbacks int4 NULL,
	puntsinside20 int4 NULL,
	longpunt int4 NULL,
	xpsuccess int4 NULL,
	xpattempts int4 NULL,
	fgsuccess int4 NULL,
	fgattempts int4 NULL
);