CREATE TABLE IF NOT EXISTS etl.stg_espn_schedule_future (
	league_id		smallint NULL,
	game_id			integer NULL,
	gamedate		timestamptz NULL,
	name			text NULL,
	shortname		text NULL,
	season_year		smallint NULL,
	season_type		smallint NULL,
	season_slug		text NULL,
	status_period	smallint NULL,
	home_score		smallint NULL,
	home_team		text NULL,
	home_abbr		text NULL,
	home_short		text NULL,
	home_team_id	bigint NULL,
	away_score		smallint NULL,
	away_team		text NULL,
	away_abbr		text NULL,
	away_short		text NULL,
	away_team_id	bigint NULL
);
