CREATE TABLE IF NOT EXISTS api.stg_foot_espn_game_team_summary (
	event_id int8 NOT NULL,
	gamedate timestamp NULL,
	season int4 NULL,
	season_type int4 NULL,
	gameweek int4 NULL,
	venue_full_name varchar(150) NULL,
	venue_city varchar(100) NULL,
	venue_state varchar(50) NULL,
	venue_zip varchar(20) NULL,
	venue_country varchar(50) NULL,
	venue_grass bool NULL,
	attendance int4 NULL,
	status_type varchar(50) NULL,
	status_detail varchar(50) NULL,
	neutral_site bool NULL,
	conference_competition bool NULL,
	team_id int4 NOT NULL,
	team_abbr varchar(10) NULL,
	team_name varchar(100) NULL,
	home_away varchar(10) NULL,
	team_score int4 NULL,
	spread numeric(5, 2) NULL,
	over_under numeric(5, 2) NULL,
	firstdowns int4 NULL,
	firstdownspassing int4 NULL,
	firstdownsrushing int4 NULL,
	firstdownspenalty int4 NULL,
	totaloffensiveplays int4 NULL,
	totalyards int4 NULL,
	yardsperplay numeric(5, 2) NULL,
	totaldrives int4 NULL,
	netpassingyards int4 NULL,
	yardsperpass numeric(5, 2) NULL,
	interceptions int4 NULL,
	rushingyards int4 NULL,
	rushingattempts int4 NULL,
	yardsperrushattempt numeric(5, 2) NULL,
	turnovers int4 NULL,
	fumbleslost int4 NULL,
	defensivetouchdowns int4 NULL,
	possessiontime interval NULL,
	passingcompletions int4 NULL,
	passingattempts int4 NULL,
	thirddownsuccess int4 NULL,
	thirddownattempts int4 NULL,
	fourthdownsuccess int4 NULL,
	fourthdownattempts int4 NULL,
	sacks int4 NULL,
	sackyardslost int4 NULL,
	redzonesuccess numeric(5, 2) NULL,
	penalties int4 NULL,
	penaltyyards int4 NULL
);