CREATE TABLE IF NOT EXISTS api.stg_foot_espn_box_offensive (
	event_id int8 NOT NULL,
	team_id int4 NOT NULL,
	team_abbr varchar(10) NULL,
	team_name varchar(100) NULL,
	athlete_id int8 NULL,
	athlete_name varchar(100) NULL,
	athlete_jersey varchar(10) NULL,
	passingyards int4 NULL,
	yardsperpassattempt numeric(5, 2) NULL,
	passingtouchdowns int4 NULL,
	interceptions int4 NULL,
	adjqbr numeric(5, 2) NULL,
	rushingattempts int4 NULL,
	rushingyards int4 NULL,
	yardsperrushattempt numeric(5, 2) NULL,
	rushingtouchdowns int4 NULL,
	longrushing int4 NULL,
	receptions int4 NULL,
	receivingyards int4 NULL,
	yardsperreception numeric(5, 2) NULL,
	receivingtouchdowns int4 NULL,
	longreception int4 NULL,
	receivingtargets int4 NULL,
	qbrating numeric(5, 2) NULL,
	passingcompletions int4 NULL,
	passingattempts int4 NULL,
	sacks int4 NULL,
	sackyardslost int4 NULL
);