create table IF NOT EXISTS odd.bbl(	-- Bridge_Bettor_League
  bbl_id bigint GENERATED BY DEFAULT AS identity,
  bettor_id bigint not NULL,
  league_id bigint not NULL,
  active boolean default (true),
  start_ts timestamp,
  end_ts timestamp,
  insert_ts timestamp not null default now()
);