CREATE TABLE odd.bet (
  bet_id bigint GENERATED BY DEFAULT AS IDENTITY,
  bet_source_id bigint,
  bet_hash varchar(32) NOT NULL, -- md5(bookmaker,game_id,team_id,line_type)
  bookmaker varchar(30) NOT NULL,		-- DraftKings, Kalshi
  game_id bigint NOT NULL,
  team_id int, -- Null for totals
  bet_type varchar(15) NOT NULL,		-- 'h2h, spread, total'
  bet_concat varchar(100), --NBA_LAL_OKC_20241015_H2H
  price float,
  points float,
  active boolean default (true),
  start_ts timestamp not NULL,
  end_ts timestamp,
  insert_ts timestamp not null default now()
);