CREATE TABLE IF NOT EXISTS odd.bet (
  bet_id        bigint GENERATED BY DEFAULT AS IDENTITY,
  bet_hash      varchar(32) NOT NULL, -- md5(bookmaker || game_id || coalesce(team_id, 'total') || bet_type)
  bet_source_id bigint,
  bookmaker     varchar(30) NOT NULL,  -- DraftKings, Kalshi
  game_id       bigint NOT NULL,
  team_id       int,                   -- null for totals
  bet_type      varchar(15) NOT NULL,  -- 'ML', 'SPR', 'OVER', 'UNDER'
  bet_concat    varchar(100),          -- NBA_LAL_OKC_20241015_ML_LAL
  price         float,
  points        float,
  active        boolean default (true),
  start_ts      timestamp not NULL,
  end_ts        timestamp,
  insert_ts     timestamp not null default now()
);
