create table odd.bettor(
  bettor_id bigint GENERATED BY DEFAULT AS identity,
  insert_ts timestamp not null default now(),
  last_login_ts timestamp not null default now(),
  google_sub varchar(100) unique not null,
  google_name varchar(100) unique not null,
  google_email varchar(300)
);