create table IF NOT EXISTS odd.bettor(
  bettor_id           bigint GENERATED BY DEFAULT AS identity,
  insert_ts           timestamp not null default now(),
  last_login_ts       timestamp not null default now(),
  apple_sub           varchar(100) unique not null,
  apple_email         varchar(300),
  apple_name          varchar(100),
  profile_name        varchar(100),
  symbol              varchar(100),
  color               varchar(100)
);