CREATE TABLE IF NOT EXISTS odd.enhancement (
    enhancement_id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enhancement_type varchar(10) NOT NULL,  -- 'clv' | 'edge' | 'team'
    edge_type        varchar(10) NOT NULL,  -- 'price' | 'unit' | 'clv' | 'team' | 'balance' | 'trigger' | 'risk'
    name             varchar(100) NOT NULL,
    description      varchar(500),
    symbol           varchar(100),
    bet_type         varchar(15),           -- non-null for CLV only ('h2h','spread','total')
    rarity           varchar(10),           -- 'dollar' | 'nickel' | 'dime' | 'whale'; edge-only
    cost             smallint,              -- base cost tier: 1 (dollar) | 2 (nickel) | 3 (dime) | 5 (whale); syndicate admins can 2x/3x/4x this
    effect           varchar(20),           -- the mechanic this edge applies, e.g. odds_add, odds_mult, stake_add, units_add, payout_mult, grant_clv, clv_duplicate, interest, refund_pct, retrigger, copy_left
    value            numeric(6, 2),         -- magnitude of `effect`
    config           jsonb NOT NULL DEFAULT '{}',  -- bespoke per-edge params: scope, condition, scaling, penalty, constraint, min_odds, max_odds, threshold, min_units, require_same_color, etc.
    active           boolean NOT NULL DEFAULT true,
    insert_ts        timestamp NOT NULL DEFAULT now(),

    CONSTRAINT chk_enhancement_type
        CHECK (enhancement_type IN ('clv', 'edge', 'team')),

    CONSTRAINT chk_edge_type
        CHECK (edge_type IN ('price', 'unit', 'clv', 'team', 'balance', 'trigger', 'risk')),

    CONSTRAINT chk_rarity
        CHECK (rarity IS NULL OR rarity IN ('dollar', 'nickel', 'dime', 'whale')),

    CONSTRAINT chk_cost
        CHECK (cost IS NULL OR cost IN (1, 2, 3, 5)),

    CONSTRAINT chk_clv_bet_type
        CHECK (
            (enhancement_type = 'clv' AND bet_type IN ('h2h', 'spread', 'total'))
            OR
            (enhancement_type <> 'clv' AND bet_type IS NULL)
        ),

    CONSTRAINT uq_clv_bet_type UNIQUE (enhancement_type, bet_type)
);
