CREATE TABLE IF NOT EXISTS odd.enhancement (
    enhancement_id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enhancement_type varchar(10) NOT NULL,  -- 'clv' | 'edge' | 'team'
    name             varchar(100) NOT NULL,
    description      varchar(500),
    bet_type         varchar(15),           -- non-null for CLV only ('h2h','spread','total')
    config           jsonb NOT NULL DEFAULT '{}',
    active           boolean NOT NULL DEFAULT true,
    insert_ts        timestamp NOT NULL DEFAULT now(),

    CONSTRAINT chk_enhancement_type
        CHECK (enhancement_type IN ('clv', 'edge', 'team')),

    CONSTRAINT chk_clv_bet_type
        CHECK (
            (enhancement_type = 'clv' AND bet_type IN ('h2h', 'spread', 'total'))
            OR
            (enhancement_type <> 'clv' AND bet_type IS NULL)
        ),

    CONSTRAINT uq_clv_bet_type UNIQUE (enhancement_type, bet_type)
);
