CREATE TABLE IF NOT EXISTS odd.enhanced (
    enhanced_id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bettor_id        bigint NOT NULL,
    syndicate_id     bigint NOT NULL,
    runner_id        bigint NULL,
    enhancement_id   bigint NOT NULL,
    team_id          int NOT NULL DEFAULT 0, -- 0 for non-Team enhancements; ball.team.team_id for Team type
    level            smallint NOT NULL DEFAULT 1,
    option_hash      varchar(32),
    active           boolean NOT NULL DEFAULT true,
    insert_ts        timestamp NOT NULL DEFAULT now(),

    CONSTRAINT chk_level_positive CHECK (level >= 1),
    CONSTRAINT uq_enhanced UNIQUE (bettor_id, syndicate_id, enhancement_id, team_id, week_id)
);
