create table IF NOT EXISTS odd.league(
  league_id bigint GENERATED BY DEFAULT AS identity,
  name varchar(100),
  description varchar(500),
  fantasy boolean default (false),		-- Fantasy are made up leagues of online analysts
  insert_ts timestamp not null default now()
);