CREATE TABLE IF NOT EXISTS odd.leg (
  leg_id    bigint GENERATED BY DEFAULT AS IDENTITY,
  insert_ts timestamp not null default now(),
  parlay_id bigint,
  bet_hash  varchar(32),
  price     float,
  price_enhanced float
);

ALTER TABLE odd.leg ADD COLUMN IF NOT EXISTS price_enhanced float;
