CREATE TABLE odd.leg (
  leg_id bigint GENERATED BY DEFAULT AS IDENTITY,
  insert_ts timestamp not null default now(),
  parlay_id bigint,
  bet_id bigint,
  price float,
  won boolean default (false),
  won_ts timestamp
);