CREATE TABLE IF NOT EXISTS odd.parlay (
  parlay_id bigint GENERATED BY DEFAULT AS IDENTITY,
  insert_ts timestamp not null default now(),
  price_mult float,
  unit_enhanced float
);

ALTER TABLE odd.parlay ADD COLUMN IF NOT EXISTS unit_enhanced float;