create table IF NOT EXISTS odd.syndicate(
  syndicate_id          bigint GENERATED BY DEFAULT AS identity,
  name                  varchar(100),
  description           varchar(500),
  code                  text DEFAULT upper(substring(replace(gen_random_uuid()::text, '-', ''), 1, 4)),
  is_public             boolean default (false),
  password              varchar(100),
  max_runner            int,
  created_by_bettor_id  bigint,
  insert_ts             timestamp not null default now()
);
