CREATE TABLE IF NOT EXISTS odd.txn (
  txn_id bigint GENERATED BY DEFAULT AS IDENTITY,
  insert_dt timestamp not null default now(),
  bettor_id bigint not NULL,
  bet_id bigint,	-- one of these has to be not null
  parlay_id bigint,	-- one of these has to be not null
  predict_id bigint,	-- one of these has to be not null
  unit float,
  price float,
  won boolean default (false),
  won_ts timestamp,
  canceled boolean default (false),
  cancel_ts timestamp
);