CREATE TABLE IF NOT EXISTS odd.txn (
  txn_id          bigint GENERATED BY DEFAULT AS IDENTITY,
  insert_dt       timestamp not null default now(),
  bettor_id       bigint not NULL,
  syndicate_id    bigint not NULL,
  bet_hash        varchar(32),
  parlay_id       bigint,
  unit            float,
  unit_vanilla    float,   -- unit before enhancement multipliers
  price           float,
  price_vanilla   float,   -- price before enhancement multipliers
  won             boolean default (false),
  won_ts          timestamp,
  canceled        boolean default (false),
  cancel_ts       timestamp,

  CONSTRAINT chk_bet_or_parlay CHECK (bet_hash IS NOT NULL OR parlay_id IS NOT NULL)
);
