CREATE TABLE IF NOT EXISTS odd.txn (
  txn_id       bigint GENERATED BY DEFAULT AS IDENTITY,
  insert_dt    timestamp not null default now(),
  bettor_id    bigint not NULL,
  syndicate_id bigint not NULL,
  bet_hash     varchar(32),
  parlay_id    bigint,
  unit         float,
  price        float,
  game_dt      date,
  txn_type_id  smallint not null default 1,
  description  varchar(500),
  canceled     boolean default (false),
  cancel_ts    timestamp,

  CONSTRAINT chk_bet_or_parlay CHECK (txn_type_id = 3 OR bet_hash IS NOT NULL OR parlay_id IS NOT NULL)
);
