CREATE TABLE IF NOT EXISTS ball.game (
  game_id bigint GENERATED BY DEFAULT AS IDENTITY,
  source_game_id int, -- ESPN Game ID
  league_id smallint NOT NULL,
  home_team_id int NOT NULL,
  away_team_id int NOT NULL,
  game_dt date NOT NULL,
  game_time time,
  game_concat varchar, --NBA_LAL_OKC_20241015	-- MLB double header?? "_2"
  h smallint,
  a smallint,
  won_team_id int,
  h1 smallint,  a1 smallint,
  h2 smallint,  a2 smallint,
  h3 smallint,  a3 smallint,
  h4 smallint,  a4 smallint,
  h5 smallint,  a5 smallint,
  h6 smallint,  a6 smallint,
  h7 smallint,  a7 smallint,
  h8 smallint,  a8 smallint,
  h9 smallint,  a9 smallint,
  h10 smallint, a10 smallint,
  insert_ts timestamp not null default now(),
  update_ts timestamp
);