CREATE TABLE IF NOT EXISTS ball.meta (
  meta_id bigint GENERATED BY DEFAULT AS IDENTITY,
  meta_type varchar(100),
  meta_key varchar(100),
  meta_keyid bigint,		-- Used to join to GAME_ID, SCHED_ID
  meta_value varchar,
  meta_source varchar(100),  
  insert_ts timestamp not null default now()
);