CREATE TABLE IF NOT EXISTS ball.rank(
  rank_id bigint GENERATED BY DEFAULT AS IDENTITY,
  next_week_id int NOT NULL,                -- 402011024
  rank_type varchar NOT NULL,  -- AP, Coach, CFB
  team_id int NOT NULL,
  rank_num smallint NOT NULL,
  insert_ts timestamp not null default now()
);