CREATE TABLE IF NOT EXISTS ball.sched (
  sched_id bigint GENERATED BY DEFAULT AS IDENTITY,
  league_id smallint NOT NULL,-- 4
  season_id int NOT NULL,     -- 402011
  week_id int,                -- 402011024
  team_id int NOT NULL,
  game_num smallint NOT NULL, -- This is # in schedule
  opp_team_id int NOT NULL,
  sched_concat varchar, --NBA_23_24_LAL_###_OKC -- ### game_num
  game_dt date,
  home boolean,
  won boolean,
  team smallint,	-- Points
  opp smallint,
  game_id bigint,	-- Filled in after Sched, ID backfilled  
  insert_ts timestamp not null default now()
);