CREATE TABLE IF NOT EXISTS ball.season (
  season_id int GENERATED BY DEFAULT AS IDENTITY,		-- LEAGUE_ID x 100000 + YYYY, EX 402011 = MLB 2011, 100K to differentiate from TEAM_ID values at 10K
  league_id smallint NOT NULL,
  season_concat varchar(20), --MLB_2024, NBA_23_24
  pre_dt date,
  reg_start_dt date,
  reg_end_dt date,
  post_start_dt date,
  champ_series_start_dt date,		-- Equal to CHAMP_DT for NFL, CHAMP_DT clinching game of 7 game series
  champ_dt date,
  yr_var varchar(10) NOT NULL,
  yr smallint,		-- Football has year as Reg season YR, all others YR as Champ Dt
  insert_ts timestamp not null default now()
);