CREATE TABLE IF NOT EXISTS ball.week (
  week_id int GENERATED BY DEFAULT AS IDENTITY,		-- Season_ID * 1000 + WW, 402011024 = MLB 2011 Week 24
  season_id int NOT NULL,
  league_id smallint NOT NULL,
  week_start_dt date NOT NULL,
  week_end_dt date NOT NULL,
  week_num smallint NOT NULL,   -- same as game for football
  week_concat varchar(20), --MLB_2024_1, NBA_23_24_1
  week_name varchar(50),   -- pre 1-4, regular, post, bowls, playoff R1-4, championship
  is_pre boolean default (false),
  is_post boolean default (false),
  insert_ts timestamp not null default now()
);