CREATE SCHEMA "DBT";


CREATE TABLE "DBT"."POSTGAME" (
  "POSTGAME_ID" bigint GENERATED BY DEFAULT AS IDENTITY,
  "SCHED_ID" int NOT NULL,
  "GAME_ID" int NOT NULL, 
  "TEAM_ID" int NOT NULL,
  "WON" bit,
  "TEAM" int,	-- Points
  "OPP" int,
  "DIFF" int,
  "TOT" int,
  "H2H_BET_ID" int,
  "H2H_WON" bit,
  "H2H_PRICE" bit,
  "SPR_BET_ID" int,
  "SPR_WON" bit,
  "SPR_PRICE" bit,
  "SPR_POINT" bit,
  "OVER_BET_ID" int,
  "OVER_WON" bit,
  "OVER_POINT" bit,
  "UND_BET_ID" int,
  "UND_WON" bit,
  "UND_POINT" bit,
  "INSERT_DT" timestamp not null default now()
);
 
CREATE TABLE "DBT"."PREGAME" (
  "PREGAME_ID" bigint GENERATED BY DEFAULT AS IDENTITY,
  "SCHED_ID" int NOT NULL,
  "GAME_ID" int NOT NULL,
  "TEAM_ID" int NOT NULL,
  "LOC" varchar,
  
  -- GAME, for current season
  "W" int,
  "L" int,
  "W_HOME" int,
  "W_STREAK" int,
  "L_STREAK" int,
  "LAST_10" varchar,
  "NET_SCORE" float,
  "TEAM_AVG_SCORE" float,
  "OPP_AVG_SCORE" float,
  "TRAVEL_MILES" int,
  "WEATHER" varchar,
  "REST_DAYS" int,
  "STAND_CONF" int,
  "STAND_DIV" int,
  
  -- MATCHUP
  "MAT_NUM" int,
  "MAT_NUM_WON" int,
  "MAT_NET_SCORE" float,
  "MAT_TEAM_AVG_SCORE" float,
  "MAT_OPP_AVG_SCORE" float,
  "MAT_NUM_MATCH_LOC" int,
  "MAT_NUM_WON_LOC" int,
  "MAT_NET_SCORE_LOC" float,
  "MAT_TEAM_AVG_SCORE_LOC" float,
  "MAT_OPP_AVG_SCORE_LOC" float,
  
  -- BET
  "NET_UNITS" float,
  "FAV_UND_RATIO" float,
  "NUM_BET" int,
  "BET_JSON" varchar,
  "H2H_PRICE_AVG" float,
  "H2H_POINT_AVG" float,
  "SPREAD_PRICE_AVG" float,
  "SPREAD_POINT_AVG" float,
  "TOTAL_PRICE_AVG" float,
  "TOTAL_POINT_AVG" float,
  "INSERT_DT" timestamp not null default now()
);

