CREATE TABLE IF NOT EXISTS utility.job (
  job_id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_name          VARCHAR(150) NOT NULL UNIQUE,
  source_schema     VARCHAR(100) NOT NULL,
  source_table      VARCHAR(200) NOT NULL,
  target_schema     VARCHAR(100) NOT NULL,
  target_table      VARCHAR(100) NOT NULL,
  transform_view    VARCHAR(200),
  load_type         VARCHAR(25) NOT NULL,
  unique_keys       VARCHAR(100),
  schedule          VARCHAR(50),
  is_active         BOOLEAN DEFAULT TRUE,
  insert_ts         timestamp not null default now()
);