CREATE TABLE IF NOT EXISTS utility.job_log (
  job_log_id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id            bigint,
  kestra_flow       varchar,
  run_status        VARCHAR(20) NOT NULL,      -- STARTED, SUCCESS, FAILED
  start_ts          timestamp not null default now(),
  end_ts            TIMESTAMP,
  rows_read         BIGINT,
  rows_written      BIGINT,
  rows_rejected     BIGINT,
  error_message     TEXT
);
