CREATE SCHEMA odd;

-- Odds API

CREATE TABLE odd.line (
  line_id bigint GENERATED BY DEFAULT AS IDENTITY,
  game_id bigint NOT NULL,
  line_type varchar(15) NOT NULL,		-- 'h2h, spread, total'
  line_concat varchar(100), --NBA_LAL_OKC_20241015_H2H
  bookmaker varchar(30),		-- DraftKings
  team_id smallint,
  price float,
  point float,
  active bit,
  start_dt timestamp not NULL,
  end_dt timestamp,
  insert_dt timestamp not null default now()
);

-- Different table for Props in future??

create table odd.bettor(
  bettor_id bigint GENERATED BY DEFAULT AS identity,
  name varchar(100),
  x_url varchar(200),
  insert_dt timestamp not null default now()
);

create table odd.league(
  league_id bigint GENERATED BY DEFAULT AS identity,
  name varchar(100),
  description varchar(500),
  fantasy bit default ('0'),		-- Fantasy are made up leagues of online analysts
  insert_dt timestamp not null default now()
);

create table odd.bbl(	-- Bridge_Bettor_League
  bbl_id bigint GENERATED BY DEFAULT AS identity,
  bettor_id bigint not NULL,
  league_id bigint not NULL,
  active bit default ('1'),
  start_dt timestamp,
  end_dt timestamp,
  insert_dt timestamp not null default now()
);

CREATE TABLE odd.txn (
  txn_id bigint GENERATED BY DEFAULT AS IDENTITY,
  insert_dt timestamp not null default now(),
  bettor_id bigint not NULL,
  line_id bigint NOT NULL,
  unit float,
  price float,
  won bit default ('0'),
  won_ts timestamp,
  canceled bit default ('0'),
  cancel_ts timestamp
);

