CREATE SCHEMA odd;

create table odd.bettor(
  bettor_id bigint GENERATED BY DEFAULT AS identity,
  name varchar(100),
  x_url varchar(200),
  insert_dt timestamp not null default now()
);

create table odd.league(
  league_id bigint GENERATED BY DEFAULT AS identity,
  name varchar(100),
  description varchar(500),
  fantasy boolean default (false),		-- Fantasy are made up leagues of online analysts
  insert_dt timestamp not null default now()
);

create table odd.bbl(	-- Bridge_Bettor_League
  bbl_id bigint GENERATED BY DEFAULT AS identity,
  bettor_id bigint not NULL,
  league_id bigint not NULL,
  active boolean default (true),
  start_dt timestamp,
  end_dt timestamp,
  insert_dt timestamp not null default now()
);

CREATE TABLE odd.bet (
  bet_id bigint GENERATED BY DEFAULT AS IDENTITY,
  bet_source_id bigint,
  bet_hash varchar(32) NOT NULL, -- md5(bookmaker,game_id,team_id,line_type)
  bookmaker varchar(30) NOT NULL,		-- DraftKings
  game_id bigint NOT NULL,
  team_id int, -- Null for totals
  bet_type varchar(15) NOT NULL,		-- 'h2h, spread, total'
  bet_concat varchar(100), --NBA_LAL_OKC_20241015_H2H
  price float,
  points float,
  active boolean default (true),
  start_dt timestamp not NULL,
  end_dt timestamp,
  insert_dt timestamp not null default now()
);

CREATE TABLE odd.parlay (
  parlay_id bigint GENERATED BY DEFAULT AS IDENTITY,
  insert_dt timestamp not null default now(),
  price_mult float,
  won boolean default (false),
  won_ts timestamp
);

CREATE TABLE odd.parlay_bets (
  pb_id bigint GENERATED BY DEFAULT AS IDENTITY,
  insert_dt timestamp not null default now(),
  parlay_id bigint,
  bet_id bigint,
  price float,
  won boolean default (false),
  won_ts timestamp
);

CREATE TABLE odd.txn (
  txn_id bigint GENERATED BY DEFAULT AS IDENTITY,
  insert_dt timestamp not null default now(),
  bettor_id bigint not NULL,
  bet_id bigint,	-- one of these has to be not null
  parlay_id bigint,	-- one of these has to be not null
  unit float,
  price float,
  won boolean default (false),
  won_ts timestamp,
  canceled boolean default (false),
  cancel_ts timestamp
);
