
CREATE TABLE api.kalshi_market (
  kalshi_market_id bigint GENERATED BY DEFAULT AS IDENTITY,
  event_ticker varchar,
  ticker varchar,
  expected_expiration_time TIMESTAMPTZ,
  title varchar,
  yes_sub_title varchar,
  volume INTEGER,
  volume_24h INTEGER,
  yes_ask INTEGER,
  yes_bid INTEGER,
  liquidity BIGINT,
  open_interest INTEGER,
  rules_primary varchar,
  status varchar,
  imported boolean default (false),
  insert_ts timestamp not null default now()
);