// Glossary for /learn/terms. `id` is the anchor other pages link to via
// <Term id="...">; keep ids stable once linked.
export const TERM_SECTIONS = ["Odds", "Bets", "Books", "Markets", "Slang", "Math", "Taxes", "League"];

export const TERMS = [
  // Odds
  { section: "Odds", id: "decimal-odds", term: "Decimal Odds", def: "The total return per $1 staked, including your stake. 2.50 returns $2.50 on a $1 bet ($1.50 profit)." },
  { section: "Odds", id: "american-odds", term: "American Odds", def: "The -110 / +150 format used by US books. A minus number is what you risk to win $100; a plus number is what you win on a $100 bet." },
  { section: "Odds", id: "fractional-odds", term: "Fractional Odds", def: "The 5/2 format, mostly used in the UK. 5/2 means you win $5 for every $2 staked." },
  { section: "Odds", id: "implied-probability", term: "Implied Probability", def: "The win chance the odds suggest: 1 ÷ decimal odds. 2.00 implies 50%; -110 (1.91) implies 52.4%." },
  { section: "Odds", id: "vig", term: "Vig / Juice", def: "Short for vigorish. The book's built-in fee on a bet, hidden inside the odds rather than charged separately." },
  { section: "Odds", id: "overround", term: "Overround", def: "How far a market's implied probabilities add up past 100%. Two sides at -110 add to 104.8%; the extra 4.8% is the book's margin." },
  { section: "Odds", id: "hold", term: "Hold", def: "The percentage of all money wagered that the book keeps. Straight bets hold around 4-5%; parlays and props often 20-30% or more." },
  { section: "Odds", id: "break-even", term: "Break-even Rate", def: "The win percentage you need just to lose nothing. At -110 it's 52.38%, so being right half the time still loses money." },
  { section: "Odds", id: "fair-odds", term: "Fair / No-vig Odds", def: "The odds with the book's margin removed, reflecting the true probability the market implies." },
  { section: "Odds", id: "favorite", term: "Favorite / Underdog", def: "The side expected to win / the side expected to lose. Favorites pay less; underdogs pay more." },
  { section: "Odds", id: "pickem", term: "Pick'em", def: "A game with no clear favorite. The spread is zero, or both sides are priced about the same." },
  { section: "Odds", id: "expected-value", term: "Expected Value (EV)", def: "The average profit or loss per bet over the long run. +EV bets make money over time, -EV bets lose it. With the vig included, almost every bet is -EV." },
  { section: "Odds", id: "roi", term: "ROI", def: "Return on investment: profit divided by total amount wagered. Even the best bettors rarely sustain more than a few percent." },

  // Bets
  { section: "Bets", id: "moneyline", term: "Moneyline", def: "Pick the winner outright, with no point spread." },
  { section: "Bets", id: "spread", term: "Point Spread", def: "A handicap that evens out a matchup. The favorite must win by more than the line; the underdog can lose by less than the line (or win) and still cover." },
  { section: "Bets", id: "total", term: "Total (Over/Under)", def: "A bet on whether the combined score lands above or below a number set by the book." },
  { section: "Bets", id: "hook", term: "Hook", def: "The half-point on a line (-3.5) that makes a tie against the spread impossible." },
  { section: "Bets", id: "push", term: "Push", def: "A tie against the line. The stake is refunded." },
  { section: "Bets", id: "parlay", term: "Parlay", def: "Multiple bets combined into one where every leg must win. The book's edge compounds on each leg." },
  { section: "Bets", id: "sgp", term: "Same-game Parlay (SGP)", def: "A parlay built from outcomes in a single game. Books price in the correlation between legs, and SGPs carry some of the highest hold in the industry." },
  { section: "Bets", id: "teaser", term: "Teaser", def: "A parlay where you move the lines in your favor in exchange for a lower payout." },
  { section: "Bets", id: "round-robin", term: "Round Robin", def: "Every possible smaller parlay from a set of picks. 4 picks in 2-leg combinations makes 6 parlays, and 6 times the parlay edge." },
  { section: "Bets", id: "prop", term: "Prop Bet", def: "A bet on something other than the final result, such as player stats or the first scorer." },
  { section: "Bets", id: "futures", term: "Futures", def: "Bets on long-term outcomes like a champion or MVP. Your money is tied up for months, often at high hold." },
  { section: "Bets", id: "live-betting", term: "Live / In-play Betting", def: "Betting while the game is happening, with odds that update every play." },
  { section: "Bets", id: "alternate-lines", term: "Alternate Lines", def: "Spreads or totals different from the main line, offered at different prices." },
  { section: "Bets", id: "cash-out", term: "Cash Out", def: "Settling a bet early at a price the book sets, usually with extra margin built in." },
  { section: "Bets", id: "hedge", term: "Hedge", def: "Betting against your own position to lock in a result or cut risk." },
  { section: "Bets", id: "middle", term: "Middle", def: "Two bets on the same game that can both win if the result lands between the two lines." },
  { section: "Bets", id: "arbitrage", term: "Arbitrage (Arb)", def: "Bets across books that guarantee a profit because their prices disagree. Books watch for it and limit arbers quickly." },

  // Books
  { section: "Books", id: "sportsbook", term: "Sportsbook / Book", def: "A company that takes bets. It sets the odds and is the other side of every wager." },
  { section: "Books", id: "handle", term: "Handle", def: "The total amount wagered with a book." },
  { section: "Books", id: "ggr", term: "GGR (Gross Gaming Revenue)", def: "Handle minus winnings paid out. The book's take before expenses." },
  { section: "Books", id: "line", term: "Line / Number", def: "The current price or spread on a bet." },
  { section: "Books", id: "opening-closing-line", term: "Opening / Closing Line", def: "The first price posted, and the final price just before the event starts." },
  { section: "Books", id: "clv", term: "Closing Line Value (CLV)", def: "Whether the price you got beat the closing price. It's the best available measure of betting skill, and exactly what books track to find winners." },
  { section: "Books", id: "line-movement", term: "Line Movement", def: "Price changes driven by betting action or news." },
  { section: "Books", id: "market-maker", term: "Market Maker (Sportsbooks)", def: "A book that sets sharp prices and accepts large bets, such as Pinnacle or Circa." },
  { section: "Books", id: "soft-book", term: "Retail / Soft Book", def: "A mass-market book that copies lines from market makers and limits winners." },
  { section: "Books", id: "limiting", term: "Limiting", def: "A book capping how much a winning bettor may wager, sometimes down to a few dollars." },
  { section: "Books", id: "account-closure", term: "Account Closure / Ban", def: "A book removing a customer entirely, usually because they win." },
  { section: "Books", id: "palp", term: "Palp / Obvious Error", def: "Short for palpable error. The rule books use to void bets they say were mispriced, which almost always means bets they lost." },
  { section: "Books", id: "max-bet", term: "Max Bet / Bet Limit", def: "The largest stake a book will accept on a bet." },
  { section: "Books", id: "promo", term: "Promo / Odds Boost", def: "An improved price used for marketing, often on bets that already carry high hold." },
  { section: "Books", id: "bonus-bet", term: "Bonus Bet / Site Credit", def: "Promo money where only the winnings are paid out, not the stake. A $100 bonus bet at even odds is worth about $50." },
  { section: "Books", id: "playthrough", term: "Playthrough / Rollover", def: "How much you must wager before bonus funds can be withdrawn, paying vig every time." },
  { section: "Books", id: "kyc", term: "KYC", def: "“Know Your Customer.” The identity verification required to bet and withdraw. It ties every account to one real person." },
  { section: "Books", id: "geofencing", term: "Geofencing", def: "Location checks that confirm you're in a state where betting is legal." },
  { section: "Books", id: "bearding", term: "Bearding", def: "Placing bets through someone else's account, usually after being limited. It breaks book rules and can be prosecuted as fraud, a felony in many states." },
  { section: "Books", id: "offshore-book", term: "Offshore Book", def: "An unlicensed site operating outside US regulation, with no guarantee you'll ever be paid." },
  { section: "Books", id: "responsible-gaming", term: "Responsible Gaming Tools", def: "Deposit limits, time limits, and cool-off periods that books are required to offer." },
  { section: "Books", id: "self-exclusion", term: "Self-exclusion", def: "Voluntarily banning yourself from betting, at one book or statewide." },

  // Markets
  { section: "Markets", id: "prediction-market", term: "Prediction Market", def: "An exchange where users trade contracts on real-world outcomes." },
  { section: "Markets", id: "event-contract", term: "Event Contract", def: "A yes/no contract that pays a fixed amount, such as $1, if the event happens and nothing if it doesn't." },
  { section: "Markets", id: "exchange", term: "Exchange vs. Sportsbook", def: "On an exchange you trade against other users, not the house. The exchange profits from fees instead of your losses." },
  { section: "Markets", id: "price-as-probability", term: "Price as Probability", def: "A contract priced at $0.62 implies a 62% chance of the event happening." },
  { section: "Markets", id: "bid-ask", term: "Bid / Ask / Spread", def: "The best price to buy, the best price to sell, and the gap between them." },
  { section: "Markets", id: "order-book", term: "Order Book", def: "The list of open buy and sell orders on a contract." },
  { section: "Markets", id: "liquidity", term: "Liquidity", def: "How much can be traded without moving the price." },
  { section: "Markets", id: "pm-market-maker", term: "Market Maker (Prediction Markets)", def: "A firm that keeps posting buy and sell orders on both sides of a contract so others always have someone to trade with, earning the bid/ask spread. Big sportsbooks are entering prediction markets in this role, which puts the house back on the other side of many trades." },
  { section: "Markets", id: "market-taker", term: "Market Taker", def: "A trader who fills an order already on the order book instead of posting a new one. Takers pay the spread and usually the higher fee. Most casual traders are takers." },
  { section: "Markets", id: "maker-taker", term: "Maker / Taker Fees", def: "Fees for adding liquidity (maker) versus taking existing orders (taker). The exchange's version of the vig." },
  { section: "Markets", id: "resolution", term: "Resolution", def: "How and when a contract is settled, and by whose rules." },
  { section: "Markets", id: "cftc", term: "CFTC", def: "The Commodity Futures Trading Commission, the federal regulator that oversees event contracts." },
  { section: "Markets", id: "kalshi-polymarket", term: "Kalshi / Polymarket", def: "The major current prediction market platforms. Named here as examples, not endorsements." },
  { section: "Markets", id: "regulatory-gray-area", term: "Regulatory Gray Area", def: "As of 2026, whether sports event contracts fall under federal commodity rules or state gaming law is actively contested in courts and legislatures." },

  // Slang
  { section: "Slang", id: "sharp", term: "Sharp", def: "A skilled, winning bettor. Books limit sharps quickly." },
  { section: "Slang", id: "square", term: "Square / Public / Recreational", def: "A casual bettor. Books welcome squares and send them promos." },
  { section: "Slang", id: "whale", term: "Whale", def: "A very high-stakes bettor." },
  { section: "Slang", id: "degen", term: "Degen", def: "A compulsive or reckless bettor. Often worn as a badge of honor, which is worth noticing: it makes a real problem sound like a personality." },
  { section: "Slang", id: "unit", term: "Unit", def: "A standard bet size, usually 1-2% of bankroll. In UNIT League, units are the fake currency you play with." },
  { section: "Slang", id: "bankroll", term: "Bankroll", def: "Money set aside only for betting. In UNIT League, your unit balance." },
  { section: "Slang", id: "action", term: "Action", def: "Having money on a game." },
  { section: "Slang", id: "chalk", term: "Chalk", def: "The favorite, or betting favorites." },
  { section: "Slang", id: "fade", term: "Fade", def: "Betting against someone or something." },
  { section: "Slang", id: "tail", term: "Tail", def: "Copying someone else's bet." },
  { section: "Slang", id: "lock", term: "Lock", def: "A “sure thing.” There isn't one." },
  { section: "Slang", id: "steam", term: "Steam", def: "Sudden, sharp line movement across many books at once, usually from professional money." },
  { section: "Slang", id: "rlm", term: "Reverse Line Movement (RLM)", def: "The line moving against the side most of the public is betting, a sign of sharp money on the other side." },
  { section: "Slang", id: "trap-line", term: "Trap Line", def: "A line believed to bait the public into the wrong side." },
  { section: "Slang", id: "buying-points", term: "Buying Points", def: "Paying extra juice to move a line in your favor." },
  { section: "Slang", id: "sweat", term: "Sweat", def: "Nervously watching a live bet." },
  { section: "Slang", id: "bad-beat", term: "Bad Beat", def: "Losing a bet that looked won late in the game." },
  { section: "Slang", id: "backdoor-cover", term: "Backdoor Cover", def: "A late, meaningless score that decides the spread." },
  { section: "Slang", id: "cooked", term: "Cooked / Got There", def: "Lost / won." },
  { section: "Slang", id: "tout", term: "Tout / Capper", def: "Someone selling picks. Ask the obvious question: if they could reliably win, why would they sell?" },
  { section: "Slang", id: "chasing", term: "Chasing", def: "Betting more to recover losses. One of the clearest warning signs of problem gambling." },
  { section: "Slang", id: "tilt", term: "Tilt", def: "Emotional, impaired betting after losses." },
  { section: "Slang", id: "lotto-ticket", term: "Parlay Prayer / Lotto Ticket", def: "A long-shot parlay with a tiny chance of hitting." },

  // Math
  { section: "Math", id: "variance", term: "Variance", def: "The natural swings in results. Even a bettor with a real edge can lose for months." },
  { section: "Math", id: "sample-size", term: "Sample Size", def: "The number of bets needed before results mean anything. A hot month proves very little; it takes thousands of bets to separate skill from luck." },
  { section: "Math", id: "negative-sum", term: "Negative-sum Game", def: "A game where total money out is less than total money in. With the book taking its cut, bettors as a group always lose." },
  { section: "Math", id: "kelly-criterion", term: "Kelly Criterion", def: "A formula for sizing bets based on your edge and the odds: stake = (bp − q) ÷ b, where b is the net decimal odds, p your win chance, and q = 1 − p. Most pros bet a fraction of Kelly because it assumes you know your edge exactly. Its precise, odd-looking stakes are also a red flag to books." },
  { section: "Math", id: "gamblers-fallacy", term: "Gambler's Fallacy", def: "Believing “I'm due.” Past results don't change the odds of the next bet." },
  { section: "Math", id: "near-miss", term: "Near-miss Effect", def: "Almost-wins, like a parlay that missed by one leg, that feel like progress and keep you betting." },
  { section: "Math", id: "sunk-cost", term: "Sunk Cost", def: "Continuing to bet because of what you've already lost." },
  { section: "Math", id: "recency-bias", term: "Recency Bias", def: "Overweighting the last few results." },

  // Taxes
  { section: "Taxes", id: "gambling-winnings", term: "Gambling Winnings", def: "Taxable income, whether or not you receive a tax form." },
  { section: "Taxes", id: "w2g", term: "W-2G", def: "The IRS form issued for certain larger gambling wins." },
  { section: "Taxes", id: "itemized-deduction", term: "Itemized Deduction", def: "You must itemize, rather than take the standard deduction, to deduct any gambling losses." },
  { section: "Taxes", id: "loss-deduction-limit", term: "Loss Deduction Limit", def: "Losses are deductible only up to your winnings, and starting in 2026 only 90% of losses count. You can owe tax in a year you lost money overall." },
  { section: "Taxes", id: "state-tax", term: "State Tax Treatment", def: "Varies by state, and some states allow no deduction for losses at all." },

  // League
  { section: "League", id: "syndicate", term: "Syndicate", def: "In UNIT League, a league of runners competing with the same starting units. In real betting, a group of professionals pooling money and information." },
  { section: "League", id: "runner", term: "Runner", def: "A player in a UNIT League syndicate. Each runner has their own unit balance and Juice." },
  { section: "League", id: "juice-unit-league", term: "Juice (UNIT League)", def: "In UNIT League, Juice is the enhancements you add to a runner (CLV, Team, and Edge cards) that change odds, stakes, or payouts. The opposite of the sportsbook meaning: it works for you." },
];
